/**
 * Color Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const colors = {
  "primary-800": {
    "1396:1": "#000000"
  },
  "primary-600": {
    "1396:1": "#212121"
  },
  "secondary-400": {
    "1396:1": "#c2c2c2"
  },
  "ss-foreground": {
    "1396:1": "#ffffff"
  },
  "ss-background": {
    "1396:1": "#f7f7f2"
  }
} as const;

export type ColorToken = keyof typeof colors;

/**
 * Helper to get color value for a specific mode
 */
export function getColor(token: ColorToken, modeId?: string): string {
  const colorValue = colors[token];
  if (!colorValue) return '#000000';
  
  if (modeId && (colorValue as any)[modeId]) {
    return (colorValue as any)[modeId];
  }
  return Object.values(colorValue)[0] as string;
}
