/**
 * Border Radius Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const radius = {
  none: 0,
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  '2xl': 24,
  full: 9999, // For circular elements
  
  // Component-specific radius
  button: 8,
  input: 8,
  card: 12,
  modal: 16,
} as const;

export type RadiusToken = keyof typeof radius;