/**
 * Border Radius Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const radius = {
  "corner-radius-1": {
    "1396:2": 23
  },
  "corner-radius-2": {
    "1396:2": 12
  }
} as const;

export type RadiusToken = keyof typeof radius;

/**
 * Helper to get radius value for a specific mode
 */
export function getRadius(token: RadiusToken, modeId?: string): number {
  const radiusValue = radius[token];
  if (typeof radiusValue === 'object' && modeId) {
    return (radiusValue as any)[modeId] || Object.values(radiusValue)[0] as number;
  }
  if (typeof radiusValue === 'object') {
    return Object.values(radiusValue)[0] as number;
  }
  return radiusValue as number;
}
