/**
 * Shadow Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const shadows = {
  "sm": {
    "shadowColor": "#000",
    "shadowOffset": {
      "width": 0,
      "height": 1
    },
    "shadowOpacity": 0.18,
    "shadowRadius": 1,
    "elevation": 1
  },
  "md": {
    "shadowColor": "#000",
    "shadowOffset": {
      "width": 0,
      "height": 2
    },
    "shadowOpacity": 0.23,
    "shadowRadius": 2.62,
    "elevation": 4
  },
  "lg": {
    "shadowColor": "#000",
    "shadowOffset": {
      "width": 0,
      "height": 4
    },
    "shadowOpacity": 0.3,
    "shadowRadius": 4.65,
    "elevation": 8
  }
} as const;

export type ShadowToken = keyof typeof shadows;
