/**
 * Spacing Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const spacing = {
  "spacing-s": {
    "1396:0": 7
  },
  "spacing-m": {
    "1396:0": 11
  },
  "spacing-l": {
    "1396:0": 14
  },
  "spacing-xl": {
    "1396:0": 21
  },
  "corner-radius-1": {
    "1396:2": 23
  },
  "corner-radius-2": {
    "1396:2": 12
  }
} as const;

export type SpacingToken = keyof typeof spacing;

/**
 * Helper to get spacing value for a specific mode
 */
export function getSpacing(token: SpacingToken, modeId?: string): number {
  const spacingValue = spacing[token];
  if (typeof spacingValue === 'object' && modeId) {
    return (spacingValue as any)[modeId] || Object.values(spacingValue)[0] as number;
  }
  if (typeof spacingValue === 'object') {
    return Object.values(spacingValue)[0] as number;
  }
  return spacingValue as number;
}
