/**
 * Spacing Design Tokens
 * Auto-generated from Figma Variables
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-tokens.js
 */

export const spacing = {
  // Base spacing unit (4px)
  base: 4,
  
  // Spacing scale (multiples of base)
  xs: 4,    // 4px
  sm: 8,    // 8px
  md: 16,   // 16px
  lg: 24,   // 24px
  xl: 32,   // 32px
  '2xl': 48, // 48px
  '3xl': 64, // 64px
  '4xl': 96, // 96px
  
  // Component-specific spacing
  button: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    gap: 8,
  },
  input: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  card: {
    padding: 16,
    gap: 12,
  },
} as const;

export type SpacingToken = keyof typeof spacing;